server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.contract.entity
